### ISSUE TITLE
Setting Swiper Loop Option to True Error

### ISSUE THREAD

**Issue by beastmst** [Ember-Swiper/ember-cli-swiper#103] opened 2018-04-25 04:11 UTC
When add the option `loop=true` to a custom Swiper, I get the error:
```
Uncaught TypeError: Cannot read property 'classList' of undefined
at swiper.js line 206
```
To reproduce the error first configure a working Swiper like so:
```hbs
{{#swiper-container
  currentSlide=1
  grabCursor=true
  loopedSlides=3
  pagination=true
  autoplay=(hash delay=9600)}}
  {{swiper-slide}}
  {{swiper-slide}}
  {{swiper-slide}}  
{{/swiper-container}}
```
then to generate the above error add the option `loop=true` to the swiper-container.

I expect the Swiper instance to work as it did before, only to automatically loop through all my slides 3 times.

**Comment by Matt-Jensen** [comment] 2018-04-25 14:32
@beastmst I've updated your issue comment to be a  bug report.  Please update with any information that's incorrect because I had to make some assumptions about your goals.

**Comment by Matt-Jensen** [comment] 2018-04-25 14:46
Unable to reproduce your error with the corrected Swiper v4 configuration options.  Closing issue unless you can reproduce the error using the above steps.

**Closed by Matt-Jensen** 2018-04-25 14:46 UTC

**Comment by beastmst** [comment] 2018-04-26 02:09
below is the steps I use to reproduce the error

ember -v
ember-cli: 3.1.2
node: 6.11.5

ember new swipertest
cd swipertest
ember install ember-cli-swiper
vi app/templates/application.hbs
delete the welcome page, and put in the bellow

{{#swiper-container currentSlide=currentSlide grabCursor=true autoplay=9600 loop=true slidesPerView=1}}
            {{#swiper-slide}}<h2>slide 1</h2>{{/swiper-slide}}
            {{#swiper-slide}}<h2>slide 2</h2>{{/swiper-slide}}
            {{#swiper-slide}}<h2>slide 3</h2>{{/swiper-slide}}
{{/swiper-container}}

**Comment by beastmst** [comment] 2018-04-26 03:13
when I switch over to ember-cli-swiper@0.7.4, the above code worked

**Comment by Matt-Jensen** [comment] 2018-04-26 03:18
The options for v0.7.4 are not intended to be 100% compatible with v1.0.0.  That's why the last release required a new major version.

FWIW the autoplay option is no longer a boolean, please use a hash instead like documented above.

**Comment by beastmst** [comment] 2018-04-26 05:41
this copied from the example page from the project... it is not working

````
{{#swiper-container

   currentSlide=currentSlide2
   loop=true
   centered=true slidesPerView=2

}}
            {{#swiper-slide}}<h2>slide 1</h2>{{/swiper-slide}}
            {{#swiper-slide}}<h2>slide 2</h2>{{/swiper-slide}}
            {{#swiper-slide}}<h2>slide 3</h2>{{/swiper-slide}}
{{/swiper-container}}
````

**Comment by Matt-Jensen** [comment] 2018-04-26 16:30
I've run both code snippets you've provided locally, confirmed the demo site is working as expected, and confirmed running the latest v1.0.0 code on both.  _Again: I'm not able to produce any bug and everything is working as expected_.

`currentSlide` is addon specific and just binds the Swiper's active slide index.  ie setting `currentSlide=2` would make the 3rd slide active.

Setting `slidesPerView=1` is redundant.

Please don't use unknown variables when submitting a bug report: `currentSlide=currentSlide` as it just adds more questions about what code you're running.

Recommend you submit a failing test to continue debugging further.

**Comment by beastmst** [comment] 2018-04-27 02:41
https://github.com/beastmst/swipertest

i created a git... you may try on your end?!

**Comment by Matt-Jensen** [comment] 2018-04-27 14:08
That project literally only has one line of code committed to a readme file.  I don't know if you are intentionally wasting our time at this point, if so that's unfortunate because OS maintainers commit their time for free.

So at this point I think it would be best if you found help elsewhere.  Best of luck.
