### ISSUE TITLE
Bug: Loading lazy load background images

### ISSUE THREAD

**Issue by raphaelns-developer** [Ember-Swiper/ember-cli-swiper#108] opened 2018-08-09 20:11 UTC
I'm using lazy load and background images, but when the banner items are added after the swiper component initialize the images are never loaded. I'm using with the following parameters:
```
{{#swiper-container
  registerAs=bannersSwiper
  lazy=(hash loadPrevNext=true loadPrevNextAmount=1 loadOnTransitionStart=false elementClass="swiper-lazy" loadingClass="swiper-lazy-loading" loadedClass="swiper-lazy-loaded" preloaderClass="swiper-lazy-preloader")
  pagination=true
  loop=true
  navigation=true
  autoplay=10000
  observer=true}}
  {{#each banners as |banner|}}
    <swiper-item>
      <a href="{{banner.urll}}" target="_blank">
      <div data-background="{{banner.imageUrl}}" class="swiper-lazy">
          <div class="swiper-lazy-preloader"></div>
      </div>
      </a>
  </swiper-item>
  {{/each}}
{{/swiper-container}}
```
The image is never loaded, so i fixed adding the `oberserver=true` parameter and calling the `load` function:
```
later(this, () => this.bannersSwiper._swiper.lazy.load(), 500);
```

**Comment by Matt-Jensen** [comment] 2018-08-09 20:26
Hey thanks @raphaelns-developer for creating this issue.

To help me wrap my head around what the issue can you update this issue with:
- Add the "Bug:" to the title if you believe this is a bug
- Update the issue to a bug report with observed behavior and expected behavior
- List the full steps to reproduce the bug, looks like you already have some example code there which is really helpful.

Thanks again, the more information we have the faster we can get this figured out!

**Comment by Matt-Jensen** [comment] 2018-08-11 17:34
I appreciate you clarifying that you believe there's a bug via the title.  Just for future reference you can write a full bug report by following [guidelines like this](https://capgemini.github.io/testing/effective-bug-reports/#anatomy-of-an-issue).  Open source maintainers really do appreciate this!

Since I don't know exactly what you're expecting, I'd just first point out that:
```hbs
<swiper-item>
...
</swiper-item>
```
Isn't documented in this addon or in the Swiper API as far as I can tell.  Maybe you're looking for `{{swiper-slide}}`?  Since this code isn't something we support I'm going to close this issue.  If you can provide code that is documented by this addon that fails to lazy load background images when expected, please reopen this issue.

**Closed by Matt-Jensen** 2018-08-11 17:34 UTC
